server:
  port: 7777
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #别名包
  type-aliases-package: com.ccb.movie.bean
  configuration:
    #匹配驼峰规则
    map-underscore-to-camel-case: true
spring:
  application:
    name: movie-management-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/movie_recommend?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: hadoop102
    port: 6379
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7003:7003/eureka
logging:
  level:
    #这个接口的调用日志以debug级别进行打印
    com.ccb.movie.feign.UserService: debug