server:
  port: 8888
spring:
  application:
    name: movie-user-serivce
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/movie_recommend?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
   host: hadoop102
   port: 6379
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7003:7003/eureka
