server:
  port: 80
spring:
  application:
    name: movie-system
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7003:7003/eureka